

TRAIN_BATCH_SIZE = 32
VALIDATION_BATCH_SIZE = 1
LSTM_UNITS = 128
DENSE_HIDDEN_UNITS = 4 * LSTM_UNITS
MAX_LEN = 256
EMBEDDING_SIZE = 300
CRAWL_EMBEDDINGS = 'embeddings/crawl-300d-2M.vec'
GLOVE_EMBEDDINGS = 'embeddings/glove.840B.300d.txt'